name: ci
on:
  push:
    tags:
      - 'v*'

job:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        users: actions/checkout@master

      - name: Create release
        users: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ' ',
          draft: false
          prerelease: false
