name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        goosarch:
        - 'darwin/amd64'
        - 'darwin/arm64'
        - 'linux/amd64'
        - 'linux/arm'
        - 'linux/arm64'
        - 'windows/386'
        - 'windows/amd64'
        - 'windows/arm'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Get Os and arch info
      run: |
          GOOSARCH=${{ matrix.goosarch }}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV

    - name: "Build"
      run: |
        go build -o "$BINARY_NAME" -v

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        title: "Development Build"
        files: ${{ env.BINARY_NAME }}
