name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: "Build"
      run: |
        # GOOS=linux GOARCH=amd64 make build
        make build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        title: "Development Build"
        files: |
          kfserving-inference-client
